#!/bin/sh /etc/rc.common
# IVI start script
# Copyright (C) 2009 Tsinghua University
IVIPATH="/home/jacky/src/ivimod/trunk"
. $IVIPATH/scripts/hgi_beacon/startup.sh
. $IVIPATH/scripts/hgi_beacon/addr.sh
. $IVIPATH/scripts/hgi_beacon/route.sh
. $IVIPATH/scripts/hgi_beacon/ivimap.sh
. $IVIPATH/scripts/hgi_beacon/log.sh
echo start ivi
